# Generated by Django 3.2.7 on 2021-12-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
