# Generated by Django 4.0 on 2021-12-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211221_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
