# Generated by Django 3.2.7 on 2022-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_zipcode_shippingaddress_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_imgs'),
        ),
    ]
