# Generated by Django 4.0 on 2022-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
