# Generated by Django 4.0 on 2022-05-01 07:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high',
            field=tinymce.models.HTMLField(default='demovalue'),
            preserve_default=False,
        ),
    ]
