# Generated by Django 4.0 on 2022-05-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_product_high'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
    ]
