# Generated by Django 4.0 on 2022-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='covidEssentials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='equipments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='others',
            field=models.BooleanField(default=True),
        ),
    ]
