# Generated by Django 4.0 on 2022-01-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categary',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categaries',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
