# Generated by Django 4.0 on 2022-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=None, upload_to='Blog_imgs'),
            preserve_default=False,
        ),
    ]
