# Generated by Django 4.0 on 2022-02-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='abc', upload_to='Blog_imgs'),
            preserve_default=False,
        ),
    ]
