# Generated by Django 4.0 on 2022-02-10 08:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
