# Generated by Django 3.2.7 on 2022-04-24 07:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='desc',
            field=models.TextField(default='bc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
