# Generated by Django 4.0 on 2022-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_hospital_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='centre_imgs'),
        ),
    ]
